POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlcnNAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjc4ODMxMzIsInVzZXJJZCI6Mn0.9geZKe57ehGMrrkRd6Nq6KtziNtdgHSj_aj1W0so9gM

{
 "name": "test event",
 "description": "initial test event",
 "location": "test location",
 "dateTime": "2025-01-01T15:30:00.000Z"
}

###

POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlcnNAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjc3ODczMjgsInVzZXJJZCI6Mn0.Ao51itUrSwNtMKPPEsZb3SxVqBFTcpYA_27CMoCOyeU

{
 "name": "another test event",
 "description": "test event",
 "location": "some location",
 "dateTime": "2025-01-01T15:30:00.000Z"
}