DELETE http://localhost:8080/events/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlcnNAZXhhbXBsZS5jb20iLCJleHAiOjE3Mjc4ODQ3NzUsInVzZXJJZCI6Mn0.8nU-X2UdFND95tBUbcdssm9j3c67sikUnH7VEq5l0jI